### PR TITLE
Mixed nonlinear diffusion example

### PR DESCRIPTION
**Pull request by dylan-copeland**
This PR adds a new example that demonstrates ROM for a time-dependent nonlinear diffusion simulation, using a mixed FEM formulation in H(div) and L2. There is a Newton solver for the implicit backward Euler time integrator, which requires a ROM version of the operator multiplication and Jacobian. It works in serial and parallel.

Note that the Schur complement formulation is only in the FOM solver and is not supported with ROM. For clarity, this formulation could be removed.

The FOM solver is not fully optimized. The GMRES solver for the linear system in each Newton iteration does not have a preconditioner, and in the sample runs GMRES takes about 100 iterations. This makes the FOM solver slower than it could be, so that the ROM solver gives greater speed-up than it should. Although the example is not completely mature, it demonstrates important concepts for the application of ROM.

### CODE REVIEW

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
Are we waiting for another approval for this PR?

**Comment by dylan-copeland** [comment]
> Are we waiting for another approval for this PR?

Good question, I guess one approval is enough for a new example (not really changing existing code). Does anyone else want to review, or are you fine with merging? @kevinhkhuynh @siuwuncheung

**Comment by kevinhkhuynh** [comment]
> 
> 
> > Are we waiting for another approval for this PR?
> 
> Good question, I guess one approval is enough for a new example (not really changing existing code). Does anyone else want to review, or are you fine with merging? @kevinhkhuynh @siuwuncheung

Looks fine to me.

**Comment by siuwuncheung** [comment]
> > > Are we waiting for another approval for this PR?
> > 
> > 
> > Good question, I guess one approval is enough for a new example (not really changing existing code). Does anyone else want to review, or are you fine with merging? @kevinhkhuynh @siuwuncheung
> 
> Looks fine to me.

Me too.

**Pull request merged**
