### PR TITLE
Fixing a bug in Matrix transpose

### PR DESCRIPTION
**Pull request by dylan-copeland**

### CODE REVIEW

**Review by siuwuncheung — APPROVED** [review]

**Review by chldkdtn — APPROVED** [review]

**Comment by kevinhkhuynh** [comment]
Was transposing not working before or was it doing redundant work?

**Review by kevinhkhuynh — APPROVED** [review]

**Comment by dylan-copeland** [comment]
> Was transposing not working before or was it doing redundant work?

It was looping over all entries, swapping A_ij with A_ji. This means the swapping was done twice, leaving the matrix unchanged. Only the upper (or lower) triangular part should be looped.

**Comment by kevinhkhuynh** [comment]
> > Was transposing not working before or was it doing redundant work?
> 
> It was looping over all entries, swapping A_ij with A_ji. This means the swapping was done twice, leaving the matrix unchanged. Only the upper (or lower) triangular part should be looped.

There are a few different Matrix transpose unit tests in libROM. It is strange to me why they passed before the bug fix and continued to pass afterwards.

**Comment by dylan-copeland** [comment]
@kevinhkhuynh In the `tests` directory, I see some tests for `transposeMult`, but not for `transpose`. Maybe a test should be added, if there is not one already.

**Pull request merged**
