### PR TITLE
Building libROM for TOSS4

### PR DESCRIPTION
**Pull request by debog**
Added the toolchain to build libROM on TOSS4 (LC/Quartz, etc). Also, needed to fix the script pulling MKL's version info since there is now column-aligning whitespace between #define vars and values in mkl_version.h

### CODE REVIEW

**Comment by chldkdtn** [comment]
@debog Thank you so much for doing this. By the way, would you mind changing the default toolchains in scripts/compile.sh to toss4, i.e., default-toss_4_x86_64_ib-librom-dev.cmake ? I tried to push this change directly to this branch, but it is complaining the authentication all of a sudden. Should I set some sort of personal access token?

**Comment by debog** [comment]
@chldkdtn Done! Re. authentication problem, after the TOSS4 update, I needed to delete the github line in my .ssh/known_hosts. Maybe you are having the same issue?

> @debog Thank you so much for doing this. By the way, would you mind changing the default toolchains in scripts/compile.sh to toss4, i.e., default-toss_4_x86_64_ib-librom-dev.cmake ? I tried to push this change directly to this branch, but it is complaining the authentication all of a sudden. Should I set some sort of personal access token?

**Comment by debog** [comment]
Given the current state of the branch, the following should happen on Quartz:
- To compile with "./scripts/compile.sh" (or with `default-toss_4_x86_64_ib-librom-dev.cmake` toolchain, you should have loaded any compiler module (Intel or GCC) and the corresponding MVAPICH2 and HDF5.
- If you explicitly specify either `gnu12-toss_4_x86_64_ib-librom-dev.cmake` or `ic21-toss_4_x86_64_ib-librom-dev.cmake` toolchains, then it shouldn't matter what modules are loaded (since the toolchains specify the full paths to the compilers and HDF5).

**Comment by chldkdtn** [comment]
This works for me. The only thing is that all the regression tests fail, but this is expected. After this PR is merged to master branch, I expect all the regression tests will be successful again.

**Review by chldkdtn — APPROVED** [review]

**Review by dylan-copeland — APPROVED** [review]

**Review by sullan2 — APPROVED** [review]

**Comment by dylan-copeland** [comment]
@debog I am manually running the regression tests on a non-toss4 machine. This should verify the code is correct, but as @chldkdtn mentioned, on toss4 we may just have to see what happens after merging this PR. The Mac CI has been broken for a long time, and we need someone to look into it.

**Comment by chldkdtn** [comment]
> @debog I am manually running the regression tests on a non-toss4 machine. This should verify the code is correct, but as @chldkdtn mentioned, on toss4 we may just have to see what happens after merging this PR. The Mac CI has been broken for a long time, and we need someone to look into it.

@dylan-copeland after this PR is merged to the master branch, we should also check if LaghosROM compiles fine with TOSS4 update.

**Comment by chldkdtn** [comment]
> @chldkdtn Is there a more rigorous way to make sure everything is okay? All my other codes are also facing this issue after the TOSS4 update. Of course, compiling with a new set of compilers (and especially, HDF5 library) introduces small differences, but it's nice to be sure.
> 
> Also, in the automated tests on github, I see that the CI/mac is failing, and the message says something about not finding a FORTRAN compiler. Any idea what's happening?
> 
> > This works for me. The only thing is that all the regression tests fail, but this is expected. After this PR is merged to master branch, I expect all the regression tests will be successful again.

@debog if you can check your Hyper DMD results with this libROM update, that would be wonderful.

**Comment by debog** [comment]
> @debog if you can check your Hyper DMD results with this libROM update, that would be wonderful.

@chldkdtn yes, I need to check the HyPar results. Right now, I am getting major regression test fails for HyPar (tests with and without libROM), so it will take me a couple of days to work my way through that.

**Pull request merged**
