### PR TITLE
add transform function

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Added transformation function.

Takes in another function which can transform the vector anyway it wishes.

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
still in progress

**Comment by kevinhkhuynh** [comment]
Hi, everyone. No need to do a serious look, but I would appreciate feedback on the function interfaces, and if you would like any additional functions, as you will be the primary users of these functions. Thank you.

**Comment by kevinhkhuynh** [comment]
I've verified that this works on a basic operator I created in Laghos.

**Comment by dylan-copeland** [comment]
Thanks Kevin, but instead of `void (*f) (const int size, double* vector)` I had in mind a function of the form `void (*f) (const int size, double* vectorIn, double* vectorOut)`. Maybe it does not make much difference, because the external code (e.g. Laghos) would need to have a special function written for this purpose, which could be of either form. For example, in MFEM operators typically have the form `Mult(const mfem::Vector &x, mfem::Vector &y)`, and a new version would need to be written of the form `Mult(double* x, double* y)`, which could alternatively be of the form `Mult(const int size, double* x)` with an auxiliary vector `y` used within and then copied to x. For convenience, it may better to support both versions (one vector and two vector arguments).

**Comment by kevinhkhuynh** [comment]
> Thanks Kevin, but instead of `void (*f) (const int size, double* vector)` I had in mind a function of the form `void (*f) (const int size, double* vectorIn, double* vectorOut)`. Maybe it does not make much difference, because the external code (e.g. Laghos) would need to have a special function written for this purpose, which could be of either form. For example, in MFEM operators typically have the form `Mult(const mfem::Vector &x, mfem::Vector &y)`, and a new version would need to be written of the form `Mult(double* x, double* y)`, which could alternatively be of the form `Mult(const int size, double* x)` with an auxiliary vector `y` used within and then copied to x. For convenience, it may be better to support both versions (one vector and two vector arguments).

No problem, Dylan. It is done. There is a slight concern that the class is littered with too many transform functions now, but I think the added convenience may be worth it.

**Comment by goxberry** [comment]
Use `std::function` instead of a function pointer; the former admits lambdas, functions, classes with appropriate definitions of `operator()`, or anything satisfying the `Callable` concept. The latter only works with functions.

**Comment by kevinhkhuynh** [comment]
That is a very good idea to make the transformer function more general, Geoffrey. I've gone ahead and switched to std::function.

**Comment by chldkdtn** [comment]
> Use `std::function` instead of a function pointer; the former admits lambdas, functions, classes with appropriate definitions of `operator()`, or anything satisfying the `Callable` concept. The latter only works with functions.

Glad to see that you are contributing, Geoff!

**Pull request merged**
