### PR TITLE
add new interpolation methods

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Add inverse distance weighting and lagrangian polynomial methods to matrix interpolation.

Switch linear solver and fix bug relating to linear solver.

### CODE REVIEW

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
Very nice!

**Comment by chldkdtn** [comment]
@dylan-copeland, Kevin told me that you are going to fix the compilation error related to "CreateSampleMesh" arguments.

**Comment by chldkdtn** [comment]
@kevinhkhuynh Do we have regression or unit test for all these mfem examples in librom?

**Review by siuwuncheung — APPROVED** [review]

**Comment by dylan-copeland** [comment]
The build issue is fixed in `master` now.

**Review by dylan-copeland — APPROVED** [review]

**Comment by kevinhkhuynh** [comment]
> @kevinhkhuynh Do we have regression or unit test for all these mfem examples in librom?

What do you mean by regression test for the mfem examples? Is this a test to ensure that the mfem examples run?

**Comment by chldkdtn** [comment]
> > @kevinhkhuynh Do we have regression or unit test for all these mfem examples in librom?
> 
> Can you clarify what you mean by regression test for the mfem examples? Is this a test to ensure that the mfem examples run?

The regression tests are useful to make sure that any future additional implementation does not break the existing capabilities of libROM. For example, the matrix manifold interpolation capability can be checked by comparing the results of this PR with any future results that might be altered by the future addition. We already have regression tests in LaghosROM, right? This is what I meant by "regression test."

**Comment by kevinhkhuynh** [comment]
> > > @kevinhkhuynh Do we have regression or unit test for all these mfem examples in librom?
> > 
> > 
> > Can you clarify what you mean by regression test for the mfem examples? Is this a test to ensure that the mfem examples run?
> 
> The regression tests are useful to make sure that any future additional implementation does not break the existing capabilities of libROM. For example, the matrix manifold interpolation capability can be checked by comparing the results of this PR with any future results that might be altered by the future addition. We already have regression tests in LaghosROM, right? This is what I meant by "regression test."

Ah, I see. We do not have that functionality yet. We have a unit test capability, but not a regression test capability for the mfem examples. There isn't any unit tests for matrix interpolation yet, but I can see about adding some.

**Pull request merged**
