### PR TITLE
Fix missing references when compiling with OpenMPI

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Tested on Manjaro

### CODE REVIEW

**Comment by chldkdtn** [comment]
@pranav-vempati can you check if this work in our LC machine with openMPI?

**Comment by pranav-vempati** [comment]
@sanguinariojoe in view of PR#154, which supersedes this, can this be closed?

**Comment by sanguinariojoe** [comment]
I would say so. I was just waiting until https://github.com/mfem/mfem/pull/3298 unblocks #154 to ask for closing this

**Comment by chldkdtn** [comment]
@sanguinariojoe what is the status of this PR?

**Comment by sanguinariojoe** [comment]
I am closing it. All the work on #154 is way more promising...

**Pull request closed without merging**
