### PR TITLE
Update year 2023

### PR DESCRIPTION
**Pull request by siuwuncheung**
Change the year to 2023 in the header of source files.

### CODE REVIEW

**Comment by chldkdtn** [comment]
@siuwuncheung Wow, you changed this for every single file? Wonderful. I hope you used "sed" command to accomplish this.

**Comment by siuwuncheung** [comment]
> @siuwuncheung Wow, you changed this for every single file? Wonderful. I hope you used "sed" command to accomplish this.

Yes, I did make use of `sed` to do it. :)

**Review by pranav-vempati — APPROVED** [review]

**Review by dylan-copeland — APPROVED** [review]
Why can't we do `Copyright (c) 2013-2100`?

**Comment by chldkdtn** [comment]
> Why can't we do `Copyright (c) 2013-2100`?

@dylan-copeland That is a great question. Let me check with copyright team at LLNL.

**Comment by siuwuncheung** [comment]
> > Why can't we do `Copyright (c) 2013-2100`?
> 
> @dylan-copeland That is a great question. Let me check with copyright team at LLNL.

Shall we wait until the answers from the copyright team, or just go ahead and update the year first?

**Comment by dylan-copeland** [comment]
> > > Why can't we do `Copyright (c) 2013-2100`?
> > 
> > 
> > @dylan-copeland That is a great question. Let me check with copyright team at LLNL.
> 
> Shall we wait until the answers from the copyright team, or just go ahead and update the year first?

My comment was a joke. I know that future dates are not allowed, but it doesn't make sense to me (the legal aspect is unclear to me). We got confirmation that future dates should not be used. Please go ahead and merge with 2023.

**Pull request merged**
