### PR TITLE
Create librom header file

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
1. Create libROM header file
2. Create subdirectories for libROM source files.

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
If you have any suggestions on file/directory name changes or structure changes, please let me know. The new directory structure can be viewed here: https://github.com/LLNL/libROM/tree/create_api_file

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
@dylan-copeland @siuwuncheung @jtlau when you get a chance, please review this PR.

**Comment by dylan-copeland** [comment]
> @dylan-copeland @siuwuncheung @jtlau when you get a chance, please review this PR.

I was waiting for PR 79 to get merged, since this PR depends on it, and the merge should reduce the number of changes in this PR.

**Review by jtlau — APPROVED** [review]
Works for me with SU2, thanks for alerting me of the changes.

**Review by siuwuncheung — APPROVED** [review]

**Comment by kevinhkhuynh** [comment]
Merged with master. If anyone has better ideas for names, let me know.

**Review by dylan-copeland — APPROVED** [review]

**Pull request merged**
