### PR TITLE
Parallel example bug fixes

### PR DESCRIPTION
**Pull request by dylan-copeland**
- [x] Fixed a bug in the `Options` class, by correctly setting `max_basis_dimension`. Before this fix, `max_basis_dimension` was set to the FOM dimension. In parallel, it was possible for the FOM dimension to be smaller than the number of snapshots, resulting in a failure in scalapack.
- [x] Fixed multiple examples so that they run in parallel, including
dg_advection_global_rom, linear_elasticity_global_rom, poisson_global_rom, poisson_local_rom_greedy.
- [x] Examples nonlinear_elasticity_global_rom, mixed_nonlinear_diffusion seem to have been fixed in parallel by PR 145, aside from issues resulting from the `Options` class bug.
- [x] Added relative error calculation in poisson_global_rom.
- [x] Laghos/rom regression tests pass (except for three randomized tests that fail even for the master branch).

Note that dg_advection_local_rom_matrix_interp has serial usage of frequencies.txt. For now, it only works in serial (this PR does not parallelize it).

### CODE REVIEW

**Comment by chldkdtn** [comment]
@dylan-copeland Where there any DMD examples with broken parallel functionality?

**Comment by dylan-copeland** [comment]
@chldkdtn The `-visit` issues are fixed now. The DMD examples all worked already in parallel, and their sample runs already have `mpirun -n 8`. There are no issues in parallel for DMD, because those examples simply sample snapshots from a code that orginally worked in parallel.

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
@siuwuncheung and @pranav-vempati let's review this PR.

**Comment by chldkdtn** [comment]
@siuwuncheung and @pranav-vempati let's review this PR.

**Comment by dylan-copeland** [comment]
@siuwuncheung and @pranav-vempati

**Review by siuwuncheung — APPROVED** [review]

**Pull request merged**
