### PR TITLE
Fix space-time sampling

### PR DESCRIPTION
**Pull request by dylan-copeland**
PR 274 made the temporal basis non-distributed. This PR fixes a check so that space-time ROM works in Laghos.

### CODE REVIEW

**Review by chldkdtn — APPROVED** [review]
Looks good!

**Comment by chldkdtn** [comment]
Why does "docs/readthedocs.org:librom" test fail?

**Review by dreamer2368 — APPROVED** [review]
After all CI tests pass.

**Review by siuwuncheung — APPROVED** [review]

**Comment by dylan-copeland** [comment]
readthedocs has the following error, which I don't understand. It is referring to the latest commit in this PR. @ckendrick do you have any ideas?

git checkout --force e899ef1fed32f18d32986b01ac26ed7f1457ebe8
fatal: reference is not a tree: e899ef1fed32f18d32986b01ac26ed7f1457ebe8

**Comment by ckendrick** [comment]
@dylan-copeland I'm not sure why the docs build failed here. The log seems to show it was able to clone the repo and fetch the branch correctly.

Maybe try pushing an empty commit or merging/rebasing this branch on master to kick off the build again and we can see if it still fails or not.

**Comment by dylan-copeland** [comment]
Thanks @ckendrick, the tests passed after pulling from the `master` branch. I thought the branch was up-to-date, but it wasn't.

**Pull request merged**
