### PR TITLE
merlin workflow example for heat_conduction_hdf

### PR DESCRIPTION
**Pull request by dreamer2368**
This PR has the [merlin](https://merlin.readthedocs.io/en/latest/) workflow example for heat conduction hdf. The workflow is equivalent to `examples/dmd/heat_conduction_hdf.sh`.

Neither merlin nor libROM need to be compiled together with each other. The detailed instruction for merlin installation can be found from [here](https://merlin.readthedocs.io/en/latest/tutorial/2_installation/).

The instruction for how to use this workflow is included in `examples/merlin/heat_conduction_hdf.yaml`.

### CODE REVIEW

**Comment by chldkdtn** [comment]
Introduce wiki page about Merlin in libROM repo

**Comment by dreamer2368** [comment]
[Wiki page](https://github.com/LLNL/libROM/wiki/Merlin-workflow-example-with-heat-conduction-problem) is now added.

**Review by dylan-copeland — APPROVED** [review]

**Comment by ptranq** [comment]
Can you make this run either local_tw_csv, or parametric_tw_csv, examples on the resulting data?  This is the purpose of the original script, and it would be a nice way to show the workflow automation.

**Comment by dreamer2368** [comment]
> Can you make this run either local_tw_csv, or parametric_tw_csv, examples on the resulting data? This is the purpose of the original script, and it would be a nice way to show the workflow automation.

`parametric_tw_csv` stage with time-windowing is added as the last step of the workflow.

**Review by ptranq — APPROVED** [review]

**Pull request merged**
